#!/usr/bin/env bash

##
# sweetie-bot — Automated package repository cannibaliser
# 
# Copyright © 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

echo 'Scroll acquisition program.'
echo 'The fun begins immediately!'

echo
echo

for arg in "$@"; do
    if [ "$arg" = "--water" ]; then
	echo "Augh, but the water makes me feel funny."
    fi
done

MODULES=()

echo 'Scanning...'

find '/usr/lib/sweetie-bot' | grep -v '~$' | while read module; do
    . "$module"
done

for exit_value in ${PIPESTATUS[*]}; do
    if [ ! $exit_value = 0 ]; then
	echo "Oops, an error has occurred."
	exit $exit_value
    fi
done

if [ ! ${#MODULES[@]} = 0 ]; then
    echo 'Modules located.'
else
    echo 'Insuffient about of modules, none has been locaeted!'
fi

